import { SourceTypes } from "../types/sourceTypes";

type socialNetworkType = Record<
  string,
  {
    color: string;
    name?: string;
    category:
      | "social"
      | "messaging_app"
      | "video_platform"
      | "adult"
      | "streaming"
      | "gaming"
      | "sport"
      | "ecommerce"
      | "finance"
      | "dating"
      | "other"
      | "programming"
      | "hacking"
      | "bot"
      | "search_engine"
      | "images-search-engine"
      | "paste";
  }
>;

export const socialNetworks: socialNetworkType = {
  facebook: { color: "#4267B2", category: "social" },
  twitter: { color: "#1DA1F2", category: "social" },
  instagram: { color: "#E1306C", category: "social" },
  telegram: { color: "#088CCE", category: "messaging_app" },
  whatsapp: { color: "#24CC63", category: "messaging_app" },
  skype: { color: "#08B1F1", category: "messaging_app" },
  github: { color: "#161414", category: "programming" },
  gravatar: { color: "#1C85B5", category: "social" },
  snapchat: { color: "#d8d511", category: "messaging_app" },
  youtube: { color: "#FF0000", category: "video_platform" },
  reddit: { color: "#FF4500", category: "social" },
  pinterest: { color: "#E60023", category: "social" },
  xbox: { color: "#107C10", category: "gaming" },
  playstation: { color: "#003087", category: "gaming" },
  roblox: { color: "#000000", category: "gaming", name: "Roblox" },
  mastodon: { color: "#595AFF", category: "social" },
  gitlab: { color: "#FCA121", category: "programming" },
  steam: { color: "#1D487A", category: "gaming" },
  kaggle: { color: "#20BEFF", category: "social" },
  trello: { color: "#0079BF", category: "social" },
  docker: { color: "#2496ED", category: "programming" },
  twitch: { color: "#6441A5", category: "streaming" },
  medium: { color: "#000000", category: "social" },
  flickr: { color: "#ff0084", category: "social" },
  google: { color: "#4285F4", category: "social" },
  signal: { color: "#3770E4", category: "messaging_app" },
  imgur: { color: "#2CCF96", category: "social" },
  discord: { color: "#7289DA", category: "messaging_app" },
  paypal: { color: "#003087", category: "finance" },
  quora: { color: "#B92B27", category: "social" },
  periscope: { color: "#3AA1F3", category: "social" },
  giphy: { color: "#F16063", category: "social" },
  disqus: { color: "#2E9FFF", category: "social" },
  patreon: { color: "#F96854", category: "social" },
  spotify: { color: "#1DB954", category: "streaming" },
  askfm: { color: "#FF6600", category: "social" },
  duolingo: { color: "#58CC02", category: "social" },
  airbnb: { color: "#FF5A5F", category: "social" },
  foursquare: { color: "#F94877", category: "social" },
  strava: { color: "#FC4C02", category: "sport" },
  tumblr: { color: "#001935", category: "social" },
  etsy: { color: "#F16521", category: "ecommerce" },
  fitbit: { color: "#00B0B9", category: "sport" },
  garmin: { color: "#007CC3", category: "sport" },
  notion: { color: "#000000", category: "social" },
  runkeeper: { color: "#34B2BD", category: "sport" },
  keybase: { color: "#33A0FF", category: "messaging_app" },
  runtastic: { color: "#F24E4E", category: "sport" },
  substack: { color: "#FF6719", category: "social" },
  yandex: { color: "#FC3F1D", category: "social" },
  picsart: { color: "#C209C1", category: "social" },
  taringa: { color: "#005DAB", category: "social" },
  shotgun: { color: "#433E6A", category: "social" },
  weward: { color: "#FF703F", category: "social" },
  locket: { color: "#F9B309", category: "social" },
  life360: { color: "#8652FF", category: "social" },
  clubhouse: { color: "#FFE450", category: "social" },
  eyecon: { color: "#0943B2", category: "messaging_app" },
  apple: { color: "#666666", category: "social" },
  mocospace: { color: "#C40309", category: "social" },
  teams: { color: "#5A5DB2", category: "messaging_app" },
  onedrive: { color: "#097CD5", category: "social" },
  goodreads: { color: "#824707", category: "social" },
  monopolygo: { color: "#FB2F1A", category: "gaming" },
  scrabblego: { color: "#DEB357", category: "gaming" },
  dehashed: { color: "#000000", category: "other" },
  imvu: { color: "#000000", category: "social" },
  sellix: { color: "#000000", category: "social" },
  vivino: { color: "#AA1329", category: "social" },
  whoxy: { color: "#ED8727", category: "other" },
  dropbox: { color: "#0062FF", category: "social" },
  holehe: { color: "#FF5822", category: "other" },
  foap: { color: "#60BEB9", category: "social" },
  rumble: { color: "#79A847", category: "video_platform" },
  wise: { color: "#1DBBFF", category: "finance" },
  plex: { color: "#ECB118", category: "streaming" },
  uber: { color: "#000000", category: "ecommerce" },
  box: { color: "#0061D5", category: "social" },
  mapstr: { color: "#FFB133", category: "social" },
  truecaller: { color: "#004AFF", category: "messaging_app" },
  giftful: { color: "#00BE83", category: "social" },
  pandora: { color: "#8427FC", category: "streaming" },
  pappers: { color: "#0f46a8", category: "social" },
  partiful: { color: "#000000", category: "social" },
  hudsonrock: { color: "#FDCD4E", name: "Hudson Rock", category: "other" },
  myspace: { color: "#000000", name: "MySpace", category: "social" },
  bereal: { color: "#000000", name: "BeReal", category: "social" },
  rocketreach: {
    color: "#FF3B3F",
    name: "Rocket Reach",
    category: "search_engine",
  },
  bibleapp: { color: "#A4332E", name: "BibleApp", category: "social" },
  whatsmyname: { color: "#000000", name: "WhatsMyName", category: "other" },
  wmn: { color: "#000000", name: "WhatsMyName", category: "other" },
  myfitnesspal: {
    color: "#0C8CC3",
    name: "MyFitnessPal",
    category: "sport",
  },
  protonmail: {
    color: "#8B89CC",
    name: "ProtonMail",
    category: "messaging_app",
  },
  linkedin: { color: "#087BB7", name: "LinkedIn", category: "social" },
  vk: { color: "#4C75A3", name: "VK", category: "social" },
  tiktok: { color: "#000000", name: "TikTok", category: "video_platform" },
  virustotal: { color: "#FF4B2B", name: "Virus Total", category: "social" },
  nikerunningclub: {
    color: "#F05033",
    name: "Nike Running Club",
    category: "sport", //
  },
  aboutme: { color: "#0872b4", name: "About.me", category: "social" },
  chess: { color: "#a2d060", name: "Chess.com", category: "gaming" },
  pagesjaunes: { color: "#FFDE07", name: "Pages Jaunes", category: "social" },
  copainsdavant: {
    color: "#e41129",
    name: "Copains d’avant",
    category: "social",
  },
  hibp: { color: "#000000", name: "HIBP", category: "other" },
  imageshack: { color: "#DDAE3A", name: "ImageShack", category: "social" },
  okru: { color: "#FF7700", name: "OK.ru", category: "social" },
  touchtunes: { color: "#7463D4", name: "TouchTunes", category: "social" },
  x: { color: "#000000", name: "X", category: "social" },
  isharing: { color: "#FF8150", name: "iSharing", category: "social" },
  leboncoin: { color: "#FF7421", name: "LeBonCoin", category: "ecommerce" },
  rakutendrive: { color: "#083099", name: "Rakuten Drive", category: "social" },
  beatstars: { color: "#ED170C", name: "Beat Stars", category: "social" },
  khanacademy: { color: "#18BF96", name: "Khan Academy", category: "social" },
  imapp: { color: "#EB9921", name: "iMapp", category: "social" },
  walkietalkie: {
    color: "#F7C90F",
    name: "Walkie Talkie",
    category: "messaging_app",
  },
  marcopolo: {
    color: "#FF4D00",
    name: "Marco Polo",
    category: "messaging_app",
  },
  truthsocial: { color: "#5051EC", name: "Truth Social", category: "social" },
  tvtime: { color: "#EFBF4E", name: "TV Time", category: "social" },
  qq: { color: "#1F1F1F", name: "QQ", category: "messaging_app" },
  beerbuddy: { color: "#fea233", name: "Beer Buddy", category: "social" },
  mewe: { color: "#b8d500", name: "MeWe", category: "social" },
  rutube: { color: "#333333", category: "video_platform", name: "RuTube" },
  vimeo: { color: "#1AB7EA", category: "video_platform" },
  dailymotion: {
    color: "#0066DC",
    category: "video_platform",
    name: "Dailymotion",
  },
  bitchute: { color: "#ef4138", category: "video_platform" },
  kick: { color: "#52E367", category: "video_platform" },
  odysee: { color: "#ff5512", category: "video_platform" },
  youku: { color: "#fd507f", category: "video_platform", name: "YouKu" },
  younow: { color: "#44C049", category: "video_platform", name: "YouNow" },
  xvideos: { color: "#FF0000", category: "adult", name: "XVideos" },
  pornhub: { color: "#FF9900", category: "adult", name: "PornHub" },
  chaturbate: { color: "#f8992a", category: "adult" },
  onlyfans: { color: "#1DA1F2", category: "adult", name: "OnlyFans" },
  livejasmin: { color: "#cb181c", category: "adult", name: "LiveJasmin" },
  youporn: { color: "#ea5f95", category: "adult", name: "YouPorn" },
  redtube: { color: "#FF0000", category: "adult", name: "RedTube" },
  bluesky: { color: "#00A7E4", category: "social", name: "BlueSky" },
  weibo: { color: "#E6162D", category: "social" },
  qzone: { color: "#FECE00", category: "social", name: "QZone" },
  dread: { color: "#9d5cb4", category: "social" },
  wechat: { color: "#7BB32E", category: "messaging_app" },
  messenger: { color: "#0078FF", category: "messaging_app" },
  line: { color: "#00C300", category: "messaging_app" },
  jabber: { color: "#FF7800", category: "messaging_app" },
  matrix: { color: "#000000", category: "messaging_app" },
  pastebin: { color: "#02458E", category: "paste" },
  gist: { color: "#161414", category: "programming" },
  leakbase: { color: "#1b1c15", category: "hacking", name: "LeakBase" },
  raidforums: { color: "#88748f", category: "hacking", name: "RaidForums" },
  hackforums: { color: "#282828", category: "hacking", name: "HackForums" },
  guiadohacker: {
    color: "#2970e5",
    category: "hacking",
    name: "Guia do Hacker",
  },
  breached: { color: "#7a48f6", category: "hacking" },
  breachforums: { color: "#7a48f6", category: "hacking", name: "BreachForums" },
  xss: { color: "#252c33", category: "hacking" },
  nulled: { color: "#81abc9", category: "hacking" },
  friendfinder: { color: "#f37b28", category: "dating", name: "FriendFinder" },
  tinder: { color: "#FF6B6B", category: "dating" },
  meetic: { color: "#ff1b83", category: "dating" },
  happn: { color: "#1d8bb7", category: "dating" },
  okcupid: { color: "#f851b9", category: "dating" },
  bumble: { color: "#fdc834", category: "dating" },
  nintendo_network: {
    color: "#E60012",
    category: "gaming",
    name: "Nintendo Network",
  },
  psn: { color: "#003087", category: "gaming", name: "PSN" },
  tgbot1: { color: "#1d51d1", category: "bot", name: "Homebot-1" },
  clearweb: { color: "#aaa", category: "search_engine", name: "Clear web" },
  darkweb: { color: "#000000", category: "search_engine", name: "Dark web" },
  viadeo: { color: "#ee7657", category: "social" },
  deezer: { color: "#7c2ec1", category: "streaming" },
  applemusic: { color: "#fc465b", category: "streaming", name: "Apple Music" },
  amazonmusic: {
    color: "#54d1de",
    category: "streaming",
    name: "Amazon Music",
  },
  audiomack: { color: "#f38a19", category: "streaming" },
  soundcloud: { color: "#f87d1c", category: "streaming" },
  bandcamp: { color: "#2aa3c5", category: "streaming" },
  shodan: { color: "#dc424e", category: "search_engine" },
  whiteintel: { color: "#4EA1DE", category: "other", name: "White Intel" },
  ipinfo: { color: "#066BA4", category: "other", name: "IP Info" },
  threads: { color: "#0A0A0A", category: "social" },
  typing: { color: "#59A7E7", category: "social" },
  gowish: { color: "#039BBF", category: "social", name: "GoWish" },
  bikemap: { color: "#0B73E8", category: "social", name: "BikeMap" },
  sleeper: { color: "#223353", category: "social" },
  thefork: { color: "#01675B", category: "social", name: "The Fork" },
  polarsteps: { color: "#DE2B52", category: "social" },
  facecheckid: {
    color: "#047FC5",
    category: "images-search-engine",
    name: "FaceCheck ID",
  },
  crackedio: { color: "#036B8E", category: "hacking", name: "Cracked.io" },
  psbdmp: { color: "#262557", category: "paste", name: "PSBDMP" },
  flare: { color: "#5361F2", category: "search_engine" },
  leaklookup: { color: "#293042", category: "hacking", name: "Leak-Lookup" },
  telemetry: { color: "#030711", category: "other" },
  whoisxml: { color: "#3598FB", category: "search_engine", name: "WhoisXML" },
  vinted: { color: "#147B87", category: "ecommerce" },
  replit: { color: "#FD5401", category: "programming" },
  mapmyrun: { color: "#029EEA", category: "sport", name: "Map My Run" },
  komoot: { color: "#76B52E", category: "sport" },
  microsoft: { color: "#177CD8", category: "social" },
  cashapp: { color: "#04E012", category: "finance", name: "Cash App" },
  revolut: { color: "#272D35", category: "finance" },
  mailru: { color: "#0077FF", category: "social", name: "Mail.ru" },
  newyorktimes: {
    color: "#0D0D0D",
    category: "social",
    name: "New York Times",
  },
  venmo: { color: "#068CFF", category: "finance" },
  smule: { color: "#6740F5", category: "social" },
  yelp: { color: "#D52E2B", category: "social" },
  bleacher: { color: "#000000", category: "sport" },
  pray: { color: "#0B0B0D", category: "social" },
  peloton: { color: "#171A1D", category: "sport" },
  indigo: { color: "#001B94", category: "social" },
  zepeto: { color: "#5D46FF", category: "social" },
  lidl: { color: "#1D4F90", category: "ecommerce" },
  sportstracker: { color: "#FF5933", category: "sport", name: "Sport Tracker" },
  chime: { color: "#20C074", category: "finance" },
  adobe: { color: "#FF0000", category: "other" },
  anghami: { color: "#7C52D5", category: "streaming" },
  att: { color: "#1DACE2", category: "other", name: "AT&T" },
  bajao: { color: "#B92373", category: "streaming" },
  bandlab: { color: "#EA2C17", category: "streaming" },
  blink: { color: "#1A594B", category: "social" },
  callapp: { color: "#098DF7", category: "social", name: "CallApp" },
  castbox: { color: "#F36337", category: "streaming", name: "Castbox.fm" },
  catch: { color: "#000195", category: "ecommerce" },
  coda: { color: "#E65728", category: "other" },
  costar: { color: "#696969", category: "other", name: "Co-Star" },
  cricheroes: { color: "#AD2011", category: "sport", name: "CricHeroes" },
  cricwick: { color: "#C5292E", category: "sport", name: "CricWick" },
  dailytelegraph: {
    color: "#0056B7",
    category: "other",
    name: "Daily Telegraph",
  },
  distiller: { color: "#F25A41", category: "social" },
  doordash: { color: "#DE4D2E", category: "ecommerce", name: "DoorDash" },
  easypaisa: {
    color: "#009688",
    category: "finance",
  },
  ebay: { color: "#106AD4", category: "ecommerce", name: "eBay" },
  elsa: { color: "#39AB51", category: "other" },
  explurger: {
    color: "#1150B3",
    category: "social",
  },
  fam: { color: "#FDA31F", category: "finance" },
  familylocator: {
    color: "#2570EC",
    category: "other",
    name: "Family Locator",
  },
  favicon: {
    color: "#4F46E5",
    category: "other",
    name: "FavIcon",
  },
  fiton: { color: "#3547AD", category: "sport" },
  fittr: { color: "#1C352A", category: "sport" },
  fishangler: {
    color: "#09637B",
    category: "sport",
    name: "FishAngler",
  },
  flock: { color: "#10BE52", category: "messaging_app" },
  golfnow: {
    color: "#1DAF4C",
    category: "sport",
    name: "GolfNow",
  },
  groupme: {
    color: "#1AA3EB",
    category: "messaging_app",
    name: "GroupMe",
  },
  habitshare: {
    color: "#1C96A9",
    category: "social",
  },
  halfords: {
    color: "#FF9F18",
    category: "ecommerce",
  },
  jazzbalance: {
    color: "#E91E63",
    category: "other",
    name: "Jazz Balance",
  },
  jazzcash: {
    color: "#FFC60C",
    category: "finance",
    name: "Jazz Cash",
  },
  joinr: { color: "#161616", category: "social" },
  lapse: { color: "#FF8E00", category: "social" },
  libravatar: {
    color: "#37B7D7",
    category: "other",
  },
  likewise: {
    color: "#FD7648",
    category: "social",
  },
  lineleap: {
    color: "#0882FF",
    category: "messaging_app",
    name: "LineLeap",
  },
  lovense: {
    color: "#FF2D8A",
    category: "adult",
  },
  medal: {
    color: "#621096",
    category: "streaming",
    name: "Medal",
  },
  melissa: {
    color: "#1CA7E0",
    category: "other",
    name: "Melissa",
  },
  mindbody: {
    color: "#AAFFD8",
    category: "other",
  },
  napster: {
    color: "#2A5FFF",
    category: "streaming",
  },
  numtrace: {
    color: "#000000",
    category: "other",
    name: "NumTrace",
  },
  offtop: { color: "#080808", category: "social" },
  omada: { color: "#0C7271", category: "programming" },
  paytm: { color: "#273971", category: "finance" },
  pinetwork: {
    color: "#FCB44A",
    category: "finance",
    name: "Pi Network",
  },
  pitaya: {
    color: "#F306E8",
    category: "social",
  },
  playpark: {
    color: "#00A7E1",
    category: "gaming",
    name: "Playpark.com",
  },
  playtomic: {
    color: "#345FFF",
    category: "sport",
  },
  planetfitness: {
    color: "#762A85",
    category: "sport",
    name: "Planet Fitness",
  },
  poe: { color: "#E648EB", category: "programming" },
  poshmark: { color: "#7F0254", category: "ecommerce" },
  reclip: { color: "#F7852B", category: "social" },
  regroup: { color: "#139162", category: "gaming" },
  savorfood: {
    color: "#992295",
    category: "social",
  },
  theshoecompany: {
    color: "#000000",
    category: "ecommerce",
    name: "TheShoeCompany",
  },
  skiline: {
    color: "#B90068",
    category: "sport",
  },
  sololearn: {
    color: "#F3185C",
    category: "programming",
    name: "SoloLearn",
  },
  sportxjazz: {
    color: "#101927",
    category: "sport",
    name: "Sportx Jazz",
  },
  superlocal: {
    color: "#146EFB",
    category: "other",
  },
  tapmad: {
    color: "#2BB06A",
    category: "streaming",
  },
  tellonym: {
    color: "#FF015A",
    category: "messaging_app",
  },
  templatemonster: {
    color: "#1A2A43",
    category: "ecommerce",
    name: "TemplateMonster",
  },
  tokeechat: {
    color: "#F6EB7B",
    category: "messaging_app",
    name: "Tokee Chat",
  },
  toneitup: {
    color: "#9BD7DF",
    category: "sport",
    name: "ToneItUp",
  },
  viewcaller: {
    color: "#1378CC",
    category: "messaging_app",
    name: "ViewCaller",
  },
  vibes: {
    color: "#B4A7D2",
    category: "social",
  },
  vsco: { color: "#111111", category: "social", name: "VSCO" },
  winendine: {
    color: "#073B72",
    category: "social",
  },
  w3schools: {
    color: "#20AC71",
    category: "social",
    name: "W3Schools",
  },
  wokii: {
    color: "#F9CC65",
    category: "finance",
  },
  zapier: {
    color: "#FF5813",
    category: "programming",
  },
  zenly: {
    color: "#F04F5B",
    category: "social",
  },
  untappd: {
    color: "#FFC82C",
    category: "social",
  },
  wayfair: {
    color: "#7D19A1",
    category: "ecommerce",
  },
  samsunghealth: {
    color: "#1CCD92",
    category: "sport",
    name: "Samsung Health",
  },
  wordfeud: {
    color: "#1A375F",
    category: "gaming",
  },
  classpass: {
    color: "#0156FF",
    category: "sport",
    name: "ClassPass",
  },
  fetchamericasreward: {
    color: "#F45A5C",
    category: "ecommerce",
    name: "Fetch",
  },
  twilio: {
    color: "#F22E46",
    category: "programming",
    name: "Twilio",
  },
  aliexpress: {
    color: "#E72B51",
    category: "ecommerce",
    name: "AliExpress",
  },
  telerik: {
    color: "#5DE600",
    category: "programming",
  },
  typeform: {
    color: "#262626",
    category: "programming",
  },
  fishbrain: {
    color: "#0D3155",
    category: "sport",
  },
  suno: {
    color: "#FF7717",
    category: "other",
  },
  tokee: {
    color: "#983B99",
    category: "messaging_app",
    name: "Tokee",
  },
  lusha: {
    color: "#610EFF",
    category: "social",
    name: "Lusha",
  },
  baidu: {
    color: "#2219D6",
    category: "search_engine",
    name: "Baidu",
  },
  ransomware: {
    color: "#339D72",
    category: "search_engine",
    name: "Ransomware.live",
  },
  alltrails: {
    color: "#538D2F",
    category: "sport",
    name: "AllTrails",
  },
  deviantart: {
    color: "#05CC47",
    category: "social",
    name: "DeviantArt",
  },
  wattpad: {
    color: "#FF500A",
    category: "social",
    name: "Wattpad",
  },
  wikipedia: {
    color: "#000000",
    category: "other",
    name: "Wikipedia",
  },
  dealabs: {
    color: "#2D9FAA",
    category: "ecommerce",
    name: "Dealabs",
  },
  arkham: {
    color: "#6B21A8",
    category: "search_engine",
    name: "Arkham",
  },
  finch: {
    color: "#1DA1F2",
    category: "other",
    name: "Finch",
  },
  mixcloud: {
    color: "#5000FF",
    category: "streaming",
    name: "Mixcloud",
  },
  lichess: {
    color: "#000000",
    category: "gaming",
    name: "Lichess",
  },
  gitea: {
    color: "#609926",
    category: "programming",
    name: "Gitea",
  },
  stackexchange: {
    color: "#1E5397",
    category: "programming",
    name: "Stack Exchange",
  },
  mediawiki: {
    color: "#3366CC",
    category: "other",
    name: "MediaWiki",
  },
  hackernews: {
    color: "#FF6600",
    category: "social",
    name: "Hacker News",
  },
  codeforces: {
    color: "#1F8ACB",
    category: "programming",
    name: "Codeforces",
  },
  codewars: {
    color: "#B1361E",
    category: "programming",
    name: "Codewars",
  },
  gab: {
    color: "#00D178",
    category: "social",
    name: "Gab",
  },
  gettr: {
    color: "#E50000",
    category: "social",
    name: "Gettr",
  },
  gdbrowser: {
    color: "#FFB914",
    category: "gaming",
    name: "GDBrowser",
  },
  npm: {
    color: "#CB3837",
    category: "programming",
    name: "npm",
  },
  discogs: {
    color: "#333333",
    category: "streaming",
    name: "Discogs",
  },
  huggingface: {
    color: "#FFD21E",
    category: "programming",
    name: "Hugging Face",
  },
  scratch: {
    color: "#855CD6",
    category: "programming",
    name: "Scratch",
  },
  minecraft: {
    color: "#62B47A",
    category: "gaming",
    name: "Minecraft",
  },
  sourceforge: {
    color: "#FF6600",
    category: "programming",
    name: "SourceForge",
  },
  artstation: {
    color: "#13AFF0",
    category: "social",
    name: "ArtStation",
  },
  cameo: {
    color: "#EC008C",
    category: "social",
    name: "Cameo",
  },
  behance: {
    color: "#1769FF",
    category: "social",
    name: "Behance",
  },
  unsplash: {
    color: "#000000",
    category: "social",
    name: "Unsplash",
  },
  producthunt: {
    color: "#DA552F",
    category: "social",
    name: "Product Hunt",
  },
  anilist: {
    color: "#02A9FF",
    category: "social",
    name: "AniList",
  },
  arena: {
    color: "#000000",
    category: "social",
    name: "Are.na",
  },
  devto: {
    color: "#0A0A0A",
    category: "programming",
    name: "Dev.to",
  },
  faceit: {
    color: "#FF5500",
    category: "gaming",
    name: "FACEIT",
  },
  freelancer: {
    color: "#29B2FE",
    category: "other",
    name: "Freelancer",
  },
  habbo: {
    color: "#F7941E",
    category: "gaming",
    name: "Habbo",
  },
  inaturalist: {
    color: "#74AC00",
    category: "social",
    name: "iNaturalist",
  },
  kongregate: {
    color: "#F04438",
    category: "gaming",
    name: "Kongregate",
  },
  mslearn: {
    color: "#0078D4",
    category: "programming",
    name: "Microsoft Learn",
  },
  pronounspage: {
    color: "#C71585",
    category: "social",
    name: "Pronouns.page",
  },
  speedrun: {
    color: "#199C77",
    category: "gaming",
    name: "Speedrun.com",
  },
  wakatime: {
    color: "#000000",
    category: "programming",
    name: "WakaTime",
  },
  muckrack: {
    color: "#16325C",
    category: "other",
    name: "Muck Rack",
  },
  discourse: {
    color: "#000000",
    category: "social",
    name: "Discourse",
  },
  "ssh-keys": {
    color: "#DAA520",
    category: "programming",
    name: "SSH Keys",
  },
  sshkeys: {
    color: "#DAA520",
    category: "programming",
    name: "SSH Keys",
  },
  "500px": {
    color: "#222222",
    category: "social",
    name: "500px",
  },
  dribbble: {
    color: "#EA4C89",
    category: "social",
    name: "Dribbble",
  },
  lastfm: {
    color: "#D51007",
    category: "streaming",
    name: "Last.fm",
  },
  myanimelist: {
    color: "#2E51A2",
    category: "social",
    name: "MyAnimeList",
  },
  letterboxd: {
    color: "#202830",
    category: "social",
    name: "Letterboxd",
  },
  codepen: {
    color: "#000000",
    category: "programming",
    name: "CodePen",
  },
  newgrounds: {
    color: "#FDA238",
    category: "gaming",
    name: "Newgrounds",
  },
  kofi: {
    color: "#FF6433",
    category: "social",
    name: "Ko-fi",
  },
  leaks: {
    color: "#E24B4A",
    category: "hacking",
    name: "Leaks",
  },
  archiveorg: {
    color: "#666666",
    category: "other",
    name: "Internet Archive",
  },
  atcoder: {
    color: "#000000",
    category: "programming",
    name: "AtCoder",
  },
  bitbucket: {
    color: "#0052CC",
    category: "programming",
    name: "Bitbucket",
  },
  blogspot: {
    color: "#FF5722",
    category: "social",
    name: "Blogger",
  },
  cfxre: {
    color: "#F40552",
    category: "gaming",
    name: "Cfx.re",
  },
  codeberg: {
    color: "#2185D0",
    category: "programming",
    name: "Codeberg",
  },
  crates: {
    color: "#F74C00",
    category: "programming",
    name: "crates.io",
  },
  dockerhub: {
    color: "#2496ED",
    category: "programming",
    name: "Docker Hub",
  },
  fandom: {
    color: "#FA005A",
    category: "other",
    name: "Fandom",
  },
  fansly: {
    color: "#279EFF",
    category: "adult",
    name: "Fansly",
  },
  gitee: {
    color: "#C71D23",
    category: "programming",
    name: "Gitee",
  },
  hackerrank: {
    color: "#00EA64",
    category: "programming",
    name: "HackerRank",
  },
  microsoftlearn: {
    color: "#0078D4",
    category: "programming",
    name: "Microsoft Learn",
  },
  minds: {
    color: "#FED12F",
    category: "social",
    name: "Minds",
  },
  note: {
    color: "#41C9B4",
    category: "social",
    name: "note",
  },
  opencollective: {
    color: "#7FADF2",
    category: "finance",
    name: "Open Collective",
  },
  patriotswin: {
    color: "#B22234",
    category: "social",
    name: "Patriots.win",
  },
  pixelfed: {
    color: "#6366F1",
    category: "social",
    name: "Pixelfed",
  },
  pokemonshowdown: {
    color: "#16467D",
    category: "gaming",
    name: "Pokemon Showdown",
  },
  r6: {
    color: "#000000",
    category: "gaming",
    name: "Rainbow Six Siege",
  },
  redgifs: {
    color: "#E5194D",
    category: "adult",
    name: "RedGIFs",
  },
  revolutme: {
    color: "#191C1F",
    category: "finance",
    name: "Revolut.me",
  },
  steemit: {
    color: "#06D6A9",
    category: "social",
    name: "Steemit",
  },
  wordpress: {
    color: "#21759B",
    category: "social",
    name: "WordPress",
  },
  zenn: {
    color: "#3EA8FF",
    category: "programming",
    name: "Zenn",
  },
  arduinoprojecthub: {
    color: "#00878F",
    category: "programming",
    name: "Arduino Project Hub",
  },
  calendly: {
    color: "#006BFF",
    category: "other",
    name: "Calendly",
  },
  codecademy: {
    color: "#1F4056",
    category: "programming",
    name: "Codecademy",
  },
  crevado: {
    color: "#E8503A",
    category: "other",
    name: "Crevado",
  },
  datingru: {
    color: "#F2555A",
    category: "dating",
    name: "Dating.ru",
  },
  dibiz: {
    color: "#0C7C59",
    category: "other",
    name: "Dibiz",
  },
  digitalocean: {
    color: "#0080FF",
    category: "programming",
    name: "DigitalOcean",
  },
  figma: {
    color: "#F24E1E",
    category: "programming",
    name: "Figma",
  },
  gumroad: {
    color: "#FF90E8",
    category: "ecommerce",
    name: "Gumroad",
  },
  habrcareer: {
    color: "#65A3BE",
    category: "programming",
    name: "Habr Career",
  },
  hackerearth: {
    color: "#2C3454",
    category: "programming",
    name: "HackerEarth",
  },
  ifunny: {
    color: "#FFDD2D",
    category: "social",
    name: "iFunny",
  },
  osu: {
    color: "#FF66AA",
    category: "gaming",
    name: "osu!",
  },
  streamlabs: {
    color: "#80F5D2",
    category: "streaming",
    name: "Streamlabs",
  },
  tapas: {
    color: "#FFCE00",
    category: "social",
    name: "Tapas",
  },
  vero: {
    color: "#000000",
    category: "social",
    name: "Vero",
  },
  vscodemarketplace: {
    color: "#007ACC",
    category: "programming",
    name: "VS Code Marketplace",
  },
  asciinema: {
    color: "#D40000",
    category: "programming",
    name: "asciinema",
  },
  carbonmade: {
    color: "#613CB0",
    category: "other",
    name: "Carbonmade",
  },
  carrd: {
    color: "#596CAF",
    category: "other",
    name: "Carrd",
  },
  crowdin: {
    color: "#2E3340",
    category: "other",
    name: "Crowdin",
  },
  fabswingers: {
    color: "#CC0000",
    category: "adult",
    name: "FabSwingers",
  },
  fiverr: {
    color: "#1DBF73",
    category: "other",
    name: "Fiverr",
  },
  flipboard: {
    color: "#E12828",
    category: "social",
    name: "Flipboard",
  },
  freesound: {
    color: "#307BBB",
    category: "other",
    name: "Freesound",
  },
  geocaching: {
    color: "#00874D",
    category: "sport",
    name: "Geocaching",
  },
  goodgame: {
    color: "#F6931D",
    category: "gaming",
    name: "GoodGame",
  },
  ifttt: {
    color: "#000000",
    category: "other",
    name: "IFTTT",
  },
  imgsrc: {
    color: "#E8792B",
    category: "images-search-engine",
    name: "ImgSrc.ru",
  },
  interpals: {
    color: "#3B5998",
    category: "social",
    name: "InterPals",
  },
  issuu: {
    color: "#F36D5D",
    category: "social",
    name: "Issuu",
  },
  kik: {
    color: "#82BC23",
    category: "messaging_app",
    name: "Kik",
  },
  metacritic: {
    color: "#000000",
    category: "other",
    name: "Metacritic",
  },
  naverblog: {
    color: "#03C75A",
    category: "social",
    name: "Naver Blog",
  },
  pillowfort: {
    color: "#1F3A5F",
    category: "social",
    name: "Pillowfort",
  },
  slides: {
    color: "#E4637C",
    category: "other",
    name: "Slides",
  },
  tradingview: {
    color: "#131622",
    category: "finance",
    name: "TradingView",
  },
  youpic: {
    color: "#000000",
    category: "social",
    name: "YouPic",
  },
  "35photo": {
    color: "#000000",
    category: "social",
    name: "35PHOTO",
  },
  ameblo: {
    color: "#2D8C3C",
    category: "social",
    name: "Ameblo",
  },
  ao3: {
    color: "#990000",
    category: "social",
    name: "Archive of Our Own",
  },
  audiojungle: {
    color: "#00A550",
    category: "ecommerce",
    name: "AudioJungle",
  },
  championat: {
    color: "#E52E2E",
    category: "sport",
    name: "Championat",
  },
  coderwall: {
    color: "#3E8DCC",
    category: "programming",
    name: "Coderwall",
  },
  designspiration: {
    color: "#000000",
    category: "social",
    name: "Designspiration",
  },
  hackadayio: {
    color: "#1A1A1A",
    category: "programming",
    name: "Hackaday.io",
  },
  hackster: {
    color: "#2E9FE6",
    category: "programming",
    name: "Hackster",
  },
  hubpages: {
    color: "#0E7C7B",
    category: "social",
    name: "HubPages",
  },
  instructables: {
    color: "#FABF15",
    category: "social",
    name: "Instructables",
  },
  intensedebate: {
    color: "#009EE1",
    category: "other",
    name: "IntenseDebate",
  },
  pentesterlab: {
    color: "#1F2937",
    category: "hacking",
    name: "PentesterLab",
  },
  pikabu: {
    color: "#00A46C",
    category: "social",
    name: "Pikabu",
  },
  plurk: {
    color: "#FF574D",
    category: "social",
    name: "Plurk",
  },
  shopify: {
    color: "#7AB55C",
    category: "ecommerce",
    name: "Shopify",
  },
  smugmug: {
    color: "#6DB944",
    category: "social",
    name: "SmugMug",
  },
  speakerdeck: {
    color: "#009287",
    category: "social",
    name: "Speaker Deck",
  },
  subscribestar: {
    color: "#009688",
    category: "other",
    name: "SubscribeStar",
  },
  themeforest: {
    color: "#82B540",
    category: "ecommerce",
    name: "ThemeForest",
  },
  wikidot: {
    color: "#7D9BB5",
    category: "other",
    name: "Wikidot",
  },
  wishlistr: {
    color: "#F0544C",
    category: "other",
    name: "Wishlistr",
  },
  xhamster: {
    color: "#FF7300",
    category: "adult",
    name: "xHamster",
  },
  akniga: {
    color: "#E8452C",
    category: "other",
    name: "Akniga",
  },
  biosite: {
    color: "#000000",
    category: "social",
    name: "Bio.site",
  },
  buymeacoffee: {
    color: "#FFDD00",
    category: "finance",
    name: "Buy Me A Coffee",
  },
  codechef: {
    color: "#5B4638",
    category: "programming",
    name: "CodeChef",
  },
  devrant: {
    color: "#F99A66",
    category: "programming",
    name: "devRant",
  },
  geeksforgeeks: {
    color: "#2F8D46",
    category: "programming",
    name: "GeeksforGeeks",
  },
  habr: {
    color: "#65A3BE",
    category: "programming",
    name: "Habr",
  },
  inkbunny: {
    color: "#D97BA6",
    category: "adult",
    name: "Inkbunny",
  },
  justforfans: {
    color: "#1B4F8A",
    category: "adult",
    name: "JustFor.Fans",
  },
  mix: {
    color: "#FF8126",
    category: "social",
    name: "Mix",
  },
  openstreetmap: {
    color: "#7EBC6F",
    category: "other",
    name: "OpenStreetMap",
  },
  rsi: {
    color: "#3E7A9B",
    category: "gaming",
    name: "Roberts Space Industries",
  },
  setlistfm: {
    color: "#08A00A",
    category: "other",
    name: "setlist.fm",
  },
  sofurry: {
    color: "#E8A33D",
    category: "adult",
    name: "SoFurry",
  },
  tenor: {
    color: "#1D1D1D",
    category: "images-search-engine",
    name: "Tenor",
  },
  warriorforum: {
    color: "#1A1A1A",
    category: "other",
    name: "Warrior Forum",
  },
  weasyl: {
    color: "#990000",
    category: "social",
    name: "Weasyl",
  },
  wykop: {
    color: "#367DA9",
    category: "social",
    name: "Wykop",
  },
  hackerone: {
    color: "#494649",
    category: "hacking",
    name: "HackerOne",
  },
  kwai: {
    color: "#FF6600",
    category: "video_platform",
    name: "Kwai",
  },
  "7cups": {
    color: "#3DBFC4",
    category: "other",
    name: "7 Cups",
  },
  academia: {
    color: "#41454A",
    category: "other",
    name: "Academia.edu",
  },
  animeplanet: {
    color: "#E8482F",
    category: "social",
    name: "Anime-Planet",
  },
  au: {
    color: "#0080C8",
    category: "ecommerce",
    name: "Au.ru",
  },
  beacons: {
    color: "#000000",
    category: "social",
    name: "Beacons",
  },
  bookcrossing: {
    color: "#E8A33D",
    category: "social",
    name: "BookCrossing",
  },
  buzzfeed: {
    color: "#EE3322",
    category: "other",
    name: "BuzzFeed",
  },
  clapper: {
    color: "#F26722",
    category: "video_platform",
    name: "Clapper",
  },
  cloudflarecommunity: {
    color: "#F38020",
    category: "programming",
    name: "Cloudflare Community",
  },
  codtracker: {
    color: "#E2342D",
    category: "gaming",
    name: "COD Tracker",
  },
  colourlovers: {
    color: "#000000",
    category: "social",
    name: "COLOURlovers",
  },
  comicvine: {
    color: "#1B2838",
    category: "social",
    name: "Comic Vine",
  },
  creativemarket: {
    color: "#00B34F",
    category: "ecommerce",
    name: "Creative Market",
  },
  curseforge: {
    color: "#F16436",
    category: "gaming",
    name: "CurseForge",
  },
  depop: {
    color: "#FF0000",
    category: "ecommerce",
    name: "Depop",
  },
  diigo: {
    color: "#3A88D6",
    category: "other",
    name: "Diigo",
  },
  directme: {
    color: "#000000",
    category: "social",
    name: "Direct.me",
  },
  eksisozluk: {
    color: "#81C14B",
    category: "social",
    name: "Ekşi Sözlük",
  },
  exophase: {
    color: "#3D7AB5",
    category: "gaming",
    name: "Exophase",
  },
  furaffinity: {
    color: "#36566F",
    category: "adult",
    name: "Fur Affinity",
  },
  gamefaqs: {
    color: "#294A82",
    category: "gaming",
    name: "GameFAQs",
  },
  inkitt: {
    color: "#1D1D1D",
    category: "social",
    name: "Inkitt",
  },
  itchio: {
    color: "#FA5C5C",
    category: "gaming",
    name: "itch.io",
  },
  jvc: {
    color: "#E8102E",
    category: "gaming",
    name: "Jeuxvideo.com",
  },
  kaskus: {
    color: "#1B65B3",
    category: "social",
    name: "Kaskus",
  },
  kickstarter: {
    color: "#05CE78",
    category: "finance",
    name: "Kickstarter",
  },
  librarything: {
    color: "#251A15",
    category: "social",
    name: "LibraryThing",
  },
  linuxorgru: {
    color: "#FCC624",
    category: "programming",
    name: "Linux.org.ru",
  },
  livelib: {
    color: "#E8A33D",
    category: "social",
    name: "LiveLib",
  },
  moddb: {
    color: "#CC0000",
    category: "gaming",
    name: "ModDB",
  },
  musescore: {
    color: "#1A70B8",
    category: "other",
    name: "MuseScore",
  },
  musicboard: {
    color: "#5B2CE8",
    category: "social",
    name: "Musicboard",
  },
  nexusmods: {
    color: "#DA8E35",
    category: "gaming",
    name: "Nexus Mods",
  },
  paypalme: {
    color: "#002991",
    category: "finance",
    name: "PayPal.Me",
  },
  quizlet: {
    color: "#4255FF",
    category: "other",
    name: "Quizlet",
  },
  redbubble: {
    color: "#E41321",
    category: "ecommerce",
    name: "Redbubble",
  },
  stackshare: {
    color: "#0690FA",
    category: "programming",
    name: "StackShare",
  },
  stripchat: {
    color: "#F04E23",
    category: "adult",
    name: "Stripchat",
  },
  superlink: {
    color: "#3DCC8F",
    category: "social",
    name: "Superlink",
  },
  tvtropes: {
    color: "#2B6E45",
    category: "other",
    name: "TV Tropes",
  },
  ultimateguitar: {
    color: "#FFCC00",
    category: "other",
    name: "Ultimate Guitar",
  },
  zillow: {
    color: "#006AFF",
    category: "ecommerce",
    name: "Zillow",
  },
  alternativeto: {
    color: "#0289D5",
    category: "other",
    name: "AlternativeTo",
  },
  backstage: {
    color: "#000000",
    category: "other",
    name: "Backstage",
  },
  biolink: {
    color: "#000000",
    category: "social",
    name: "Bio Link",
  },
  boardgamegeek: {
    color: "#FF5100",
    category: "gaming",
    name: "BoardGameGeek",
  },
  cyberdefenders: {
    color: "#335EEA",
    category: "hacking",
    name: "CyberDefenders",
  },
  douban: {
    color: "#2D963D",
    category: "social",
    name: "Douban",
  },
  exercism: {
    color: "#009CAB",
    category: "programming",
    name: "Exercism",
  },
  genius: {
    color: "#FFFF64",
    category: "other",
    name: "Genius",
  },
  gitbook: {
    color: "#BBDDE5",
    category: "programming",
    name: "GitBook",
  },
  gofundme: {
    color: "#00B964",
    category: "finance",
    name: "GoFundMe",
  },
  gog: {
    color: "#86328A",
    category: "gaming",
    name: "GOG.com",
  },
  hackmd: {
    color: "#453AFF",
    category: "programming",
    name: "HackMD",
  },
  hashnode: {
    color: "#2962FF",
    category: "programming",
    name: "Hashnode",
  },
  hatena: {
    color: "#00A4DE",
    category: "social",
    name: "Hatena",
  },
  hiveblog: {
    color: "#E31337",
    category: "social",
    name: "Hive Blog",
  },
  intigriti: {
    color: "#161A36",
    category: "hacking",
    name: "Intigriti",
  },
  linktree: {
    color: "#43E55E",
    category: "social",
    name: "Linktree",
  },
  microblog: {
    color: "#FF8800",
    category: "social",
    name: "Micro.blog",
  },
  ninegag: {
    color: "#000000",
    category: "social",
    name: "9GAG",
  },
  nuget: {
    color: "#004880",
    category: "programming",
    name: "NuGet",
  },
  observable: {
    color: "#353E58",
    category: "programming",
    name: "Observable",
  },
  opensea: {
    color: "#2081E2",
    category: "finance",
    name: "OpenSea",
  },
  opensanctions: {
    color: "#014FEB",
    category: "other",
    name: "OpenSanctions",
  },
  packagist: {
    color: "#F28D1A",
    category: "programming",
    name: "Packagist",
  },
  payhip: {
    color: "#5C6AC4",
    category: "ecommerce",
    name: "Payhip",
  },
  picarto: {
    color: "#1DA456",
    category: "streaming",
    name: "Picarto.TV",
  },
  platzi: {
    color: "#98CA3F",
    category: "other",
    name: "Platzi",
  },
  rarible: {
    color: "#FEDA03",
    category: "finance",
    name: "Rarible",
  },
  reverbnation: {
    color: "#E43526",
    category: "streaming",
    name: "ReverbNation",
  },
  rive: {
    color: "#1D1D1D",
    category: "other",
    name: "Rive",
  },
  rubygems: {
    color: "#E9573F",
    category: "programming",
    name: "RubyGems",
  },
  scribd: {
    color: "#1E7B85",
    category: "other",
    name: "Scribd",
  },
  sessionize: {
    color: "#1AB394",
    category: "other",
    name: "Sessionize",
  },
  sketchfab: {
    color: "#1CAAD9",
    category: "other",
    name: "Sketchfab",
  },
  slashdot: {
    color: "#026664",
    category: "social",
    name: "Slashdot",
  },
  slideshare: {
    color: "#008ED2",
    category: "other",
    name: "SlideShare",
  },
  sourcehut: {
    color: "#000000",
    category: "programming",
    name: "SourceHut",
  },
  stackblitz: {
    color: "#1269D3",
    category: "programming",
    name: "StackBlitz",
  },
  threadless: {
    color: "#0099FF",
    category: "ecommerce",
    name: "Threadless",
  },
  tistory: {
    color: "#000000",
    category: "social",
    name: "Tistory",
  },
  tmdb: {
    color: "#01B4E4",
    category: "other",
    name: "TMDB",
  },
  tripadvisor: {
    color: "#34E0A1",
    category: "other",
    name: "Tripadvisor",
  },
  tryhackme: {
    color: "#212C42",
    category: "hacking",
    name: "TryHackMe",
  },
  wellfound: {
    color: "#000000",
    category: "other",
    name: "Wellfound",
  },
  writeas: {
    color: "#5AC4EE",
    category: "social",
    name: "Write.as",
  },
  allmylinks: {
    color: "#FD4281",
    category: "social",
    name: "AllMyLinks",
  },
  allthingsworn: {
    color: "#ED0878",
    category: "adult",
    name: "All Things Worn",
  },
  apsense: {
    color: "#070607",
    category: "social",
    name: "APSense",
  },
  aryion: {
    color: "#849ACB",
    category: "adult",
    name: "Aryion",
  },
  authortoday: {
    color: "#48535E",
    category: "social",
    name: "Author.Today",
  },
  backloggd: {
    color: "#13151A",
    category: "gaming",
    name: "Backloggd",
  },
  backstagecam: {
    color: "#2277F7",
    category: "adult",
    name: "Backstage.cam",
  },
  cam4: {
    color: "#F7A50C",
    category: "adult",
    name: "CAM4",
  },
  cara: {
    color: "#010713",
    category: "social",
    name: "Cara",
  },
  ccmixter: {
    color: "#3838FF",
    category: "streaming",
    name: "ccMixter",
  },
  cgtrader: {
    color: "#67C4B0",
    category: "ecommerce",
    name: "CGTrader",
  },
  chatujme: {
    color: "#14D91A",
    category: "messaging_app",
    name: "Chatujme.cz",
  },
  chollometro: {
    color: "#EAF2F8",
    category: "ecommerce",
    name: "Chollometro",
  },
  civitai: {
    color: "#1971C2",
    category: "other",
    name: "Civitai",
  },
  codecanyon: {
    color: "#81B441",
    category: "programming",
    name: "CodeCanyon",
  },
  coindrop: {
    color: "#FEB655",
    category: "finance",
    name: "Coindrop",
  },
  comeup: {
    color: "#FFEE66",
    category: "other",
    name: "ComeUp",
  },
  contactinbio: {
    color: "#25B3F9",
    category: "social",
    name: "ContactInBio",
  },
  creatorspring: {
    color: "#2E80ED",
    category: "ecommerce",
    name: "Spring",
  },
  cryptohack: {
    color: "#FCB730",
    category: "hacking",
    name: "CryptoHack",
  },
  cssbattle: {
    color: "#FEDE00",
    category: "programming",
    name: "CSSBattle",
  },
  cults3d: {
    color: "#822EF5",
    category: "other",
    name: "Cults",
  },
  dailykos: {
    color: "#F76E04",
    category: "social",
    name: "Daily Kos",
  },
  danbooru: {
    color: "#B38E6A",
    category: "images-search-engine",
    name: "Danbooru",
  },
  debank: {
    color: "#FE815F",
    category: "finance",
    name: "DeBank",
  },
  derpibooru: {
    color: "#618FC3",
    category: "images-search-engine",
    name: "Derpibooru",
  },
  domestika: {
    color: "#F02C00",
    category: "other",
    name: "Domestika",
  },
  dou: {
    color: "#030606",
    category: "programming",
    name: "DOU",
  },
  dzen: {
    color: "#202022",
    category: "social",
    name: "Dzen",
  },
  e621: {
    color: "#152F56",
    category: "adult",
    name: "e621",
  },
  ebaumsworld: {
    color: "#303BAA",
    category: "other",
    name: "eBaum's World",
  },
  eintracht: {
    color: "#E1000F",
    category: "sport",
    name: "Eintracht Frankfurt",
  },
  empowher: {
    color: "#E75836",
    category: "other",
    name: "EmpowHER",
  },
  erome: {
    color: "#000000",
    category: "adult",
    name: "EroMe",
  },
  eroprofile: {
    color: "#7674D7",
    category: "adult",
    name: "EroProfile",
  },
  fanbase: {
    color: "#30015B",
    category: "social",
    name: "Fanbase",
  },
  fanlink: {
    color: "#7479FD",
    category: "other",
    name: "FanLink",
  },
  fanvue: {
    color: "#49F264",
    category: "adult",
    name: "Fanvue",
  },
  ficwad: {
    color: "#4A6FC9",
    category: "other",
    name: "FicWad",
  },
  fixya: {
    color: "#D5D5D5",
    category: "other",
    name: "Fixya",
  },
  flightradar24: {
    color: "#FFCC00",
    category: "other",
    name: "Flightradar24",
  },
  flist: {
    color: "#5678A7",
    category: "adult",
    name: "F-List",
  },
  fragment: {
    color: "#000000",
    category: "finance",
    name: "Fragment",
  },
  fredmiranda: {
    color: "#9B3837",
    category: "images-search-engine",
    name: "Fred Miranda",
  },
  freelanceua: {
    color: "#000000",
    category: "other",
    name: "Freelance.ua",
  },
  freeones: {
    color: "#000000",
    category: "adult",
    name: "FreeOnes",
  },
  gaiaonline: {
    color: "#362826",
    category: "gaming",
    name: "Gaia Online",
  },
  geneanet: {
    color: "#35786A",
    category: "other",
    name: "Geneanet",
  },
  getallmylinks: {
    color: "#B3A8E8",
    category: "social",
    name: "GetAllMyLinks",
  },
  giantbomb: {
    color: "#DA1818",
    category: "gaming",
    name: "Giant Bomb",
  },
  hackage: {
    color: "#5E5086",
    category: "programming",
    name: "Hackage",
  },
  heavyr: {
    color: "#030303",
    category: "adult",
    name: "Heavy-R",
  },
  hotukdeals: {
    color: "#00172B",
    category: "ecommerce",
    name: "hotukdeals",
  },
  imgflip: {
    color: "#212121",
    category: "images-search-engine",
    name: "Imgflip",
  },
  itemfix: {
    color: "#2A2A2A",
    category: "video_platform",
    name: "ItemFix",
  },
  jalbum: {
    color: "#1D3900",
    category: "images-search-engine",
    name: "jAlbum",
  },
  jetpunk: {
    color: "#64BEFF",
    category: "gaming",
    name: "JetPunk",
  },
  justpasteit: {
    color: "#FFDF5C",
    category: "paste",
    name: "JustPaste.it",
  },
  koalendar: {
    color: "#4942C2",
    category: "other",
    name: "Koalendar",
  },
  lens: {
    color: "#00501E",
    category: "social",
    name: "Lens",
  },
  limetorrents: {
    color: "#78CB28",
    category: "other",
    name: "LimeTorrents",
  },
  linkme: {
    color: "#F9776A",
    category: "social",
    name: "Link.me",
  },
  linuxfr: {
    color: "#F3B707",
    category: "programming",
    name: "LinuxFr",
  },
  listal: {
    color: "#2C2C2C",
    category: "other",
    name: "Listal",
  },
  listed: {
    color: "#EAEDF6",
    category: "social",
    name: "Listed",
  },
  listography: {
    color: "#000000",
    category: "other",
    name: "Listography",
  },
  lnkbio: {
    color: "#B996F7",
    category: "social",
    name: "Lnk.Bio",
  },
  lushstories: {
    color: "#D50000",
    category: "adult",
    name: "Lush Stories",
  },
  lyricstranslate: {
    color: "#242E42",
    category: "other",
    name: "LyricsTranslate",
  },
  magiceden: {
    color: "#E42575",
    category: "finance",
    name: "Magic Eden",
  },
  manifoldgallery: {
    color: "#000000",
    category: "finance",
    name: "Manifold Gallery",
  },
  manylink: {
    color: "#222222",
    category: "social",
    name: "Many.link",
  },
  memrise: {
    color: "#FEC000",
    category: "other",
    name: "Memrise",
  },
  meneame: {
    color: "#FF6400",
    category: "social",
    name: "Menéame",
  },
  mercari: {
    color: "#FF0211",
    category: "ecommerce",
    name: "Mercari",
  },
  metalarchives: {
    color: "#6D1216",
    category: "other",
    name: "Metal Archives",
  },
  milkshake: {
    color: "#FF4716",
    category: "social",
    name: "Milkshake",
  },
  mydealz: {
    color: "#02027B",
    category: "ecommerce",
    name: "mydealz",
  },
  mydramalist: {
    color: "#015284",
    category: "other",
    name: "MyDramaList",
  },
  myfans: {
    color: "#FF3700",
    category: "adult",
    name: "Myfans",
  },
  myminifactory: {
    color: "#00C3A5",
    category: "other",
    name: "MyMiniFactory",
  },
  mynickname: {
    color: "#849A01",
    category: "other",
    name: "MyNickname",
  },
  nationstates: {
    color: "#5877F8",
    category: "gaming",
    name: "NationStates",
  },
  ngl: {
    color: "#F96636",
    category: "social",
    name: "NGL",
  },
  nineninenine: {
    color: "#EE4825",
    category: "ecommerce",
    name: "999.md",
  },
  nintendolife: {
    color: "#1A1A1A",
    category: "gaming",
    name: "Nintendo Life",
  },
  nitrotype: {
    color: "#D62A36",
    category: "gaming",
    name: "Nitro Type",
  },
  opengameart: {
    color: "#EFEBA3",
    category: "gaming",
    name: "OpenGameArt",
  },
  oshwlab: {
    color: "#3673FE",
    category: "programming",
    name: "OSHWLab",
  },
  paragraph: {
    color: "#3D65F8",
    category: "social",
    name: "Paragraph",
  },
  passes: {
    color: "#131316",
    category: "social",
    name: "Passes",
  },
  pbase: {
    color: "#6C7EBD",
    category: "images-search-engine",
    name: "PBase",
  },
  picturepush: {
    color: "#161616",
    category: "images-search-engine",
    name: "PicturePush",
  },
  pifyi: {
    color: "#0000FE",
    category: "social",
    name: "PI.FYI",
  },
  pinkbike: {
    color: "#D70302",
    category: "sport",
    name: "Pinkbike",
  },
  podchaser: {
    color: "#491D87",
    category: "streaming",
    name: "Podchaser",
  },
  polymarket: {
    color: "#1551F0",
    category: "finance",
    name: "Polymarket",
  },
  preisjaeger: {
    color: "#EAF2F8",
    category: "ecommerce",
    name: "Preisjäger",
  },
  promodescuentos: {
    color: "#91C03D",
    category: "ecommerce",
    name: "Promodescuentos",
  },
  promptbase: {
    color: "#222236",
    category: "ecommerce",
    name: "PromptBase",
  },
  proza: {
    color: "#23C340",
    category: "other",
    name: "Proza.ru",
  },
  pwonline: {
    color: "#FEC103",
    category: "gaming",
    name: "PW Online",
  },
  qbn: {
    color: "#F80647",
    category: "other",
    name: "QBN",
  },
  quotev: {
    color: "#E1E8FA",
    category: "social",
    name: "Quotev",
  },
  ramblerdating: {
    color: "#2C5B91",
    category: "dating",
    name: "Rambler Dating",
  },
  rankia: {
    color: "#195175",
    category: "finance",
    name: "Rankia",
  },
  realmeye: {
    color: "#222222",
    category: "gaming",
    name: "RealmEye",
  },
  runescape: {
    color: "#0D0D0D",
    category: "gaming",
    name: "RuneScape",
  },
  sharechat: {
    color: "#FED91C",
    category: "social",
    name: "ShareChat",
  },
  shoppy: {
    color: "#5390FE",
    category: "ecommerce",
    name: "Shoppy",
  },
  shorby: {
    color: "#6F1E86",
    category: "social",
    name: "Shorby",
  },
  slushy: {
    color: "#1E2021",
    category: "adult",
    name: "Slushy",
  },
  snackvideo: {
    color: "#000000",
    category: "video_platform",
    name: "SnackVideo",
  },
  soloto: {
    color: "#3572FD",
    category: "social",
    name: "Solo.to",
  },
  soylentnews: {
    color: "#971216",
    category: "social",
    name: "SoylentNews",
  },
  spankbang: {
    color: "#E43E59",
    category: "adult",
    name: "SpankBang",
  },
  spells8: {
    color: "#4A85B1",
    category: "other",
    name: "Spells8",
  },
  spoutible: {
    color: "#2C465E",
    category: "social",
    name: "Spoutible",
  },
  statink: {
    color: "#666666",
    category: "gaming",
    name: "stat.ink",
  },
  statuscafe: {
    color: "#8D6E4B",
    category: "social",
    name: "status.cafe",
  },
  stihi: {
    color: "#EC6713",
    category: "other",
    name: "Stihi.ru",
  },
  suicidegirls: {
    color: "#262425",
    category: "adult",
    name: "SuicideGirls",
  },
  superprofile: {
    color: "#04A6FE",
    category: "social",
    name: "SuperProfile",
  },
  superrare: {
    color: "#000000",
    category: "finance",
    name: "SuperRare",
  },
  taittsuu: {
    color: "#989898",
    category: "social",
    name: "Taittsuu",
  },
  tango: {
    color: "#FE0065",
    category: "streaming",
    name: "Tango",
  },
  teamliquid: {
    color: "#001437",
    category: "gaming",
    name: "Team Liquid",
  },
  teia: {
    color: "#E7E7E7",
    category: "finance",
    name: "Teia",
  },
  terrariaforum: {
    color: "#A6C8E5",
    category: "gaming",
    name: "Terraria Forums",
  },
  thebigboss: {
    color: "#5B79B8",
    category: "other",
    name: "BigBoss",
  },
  throne: {
    color: "#4537E2",
    category: "social",
    name: "Throne",
  },
  tiendanube: {
    color: "#2B3256",
    category: "ecommerce",
    name: "Tiendanube",
  },
  tipeee: {
    color: "#D74555",
    category: "finance",
    name: "Tipeee",
  },
  tnaflix: {
    color: "#1E1E1E",
    category: "adult",
    name: "TNAFlix",
  },
  tokopedia: {
    color: "#03AC0E",
    category: "ecommerce",
    name: "Tokopedia",
  },
  topmate: {
    color: "#E44332",
    category: "other",
    name: "Topmate",
  },
  traktrain: {
    color: "#766CFB",
    category: "streaming",
    name: "TrakTrain",
  },
  tripline: {
    color: "#CBCBCB",
    category: "other",
    name: "Tripline",
  },
  trovo: {
    color: "#19D66B",
    category: "streaming",
    name: "Trovo",
  },
  truelancer: {
    color: "#02ABC8",
    category: "other",
    name: "Truelancer",
  },
  turpravda: {
    color: "#FFC109",
    category: "other",
    name: "TurPravda",
  },
  typeracer: {
    color: "#006AB4",
    category: "gaming",
    name: "TypeRacer",
  },
  unstoppabledomains: {
    color: "#0D0D0D",
    category: "finance",
    name: "Unstoppable Domains",
  },
  vgen: {
    color: "#B8FE26",
    category: "other",
    name: "VGen",
  },
  vlr: {
    color: "#17171A",
    category: "gaming",
    name: "VLR.gg",
  },
  voicemod: {
    color: "#141517",
    category: "other",
    name: "Voicemod",
  },
  wanderlog: {
    color: "#F85940",
    category: "other",
    name: "Wanderlog",
  },
  whatnot: {
    color: "#FFDF00",
    category: "ecommerce",
    name: "Whatnot",
  },
  zora: {
    color: "#281317",
    category: "finance",
    name: "Zora",
  },
};
